<a href="https://colab.research.google.com/github/BrunaMoraisMenezesDSM/fatec_PLN_Codes/blob/master/Aula%205%20-%20Representa%C3%A7%C3%A3o%20de%20texto/%5BPLN%5DAula_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 5 - Representação de texto
## Exemplo 1 - Implementando o BoW

In [ ]:
# importação das ferramentas a serem utilizadas
from sklearn.feature_extraction.text import CountVectorizer

# criando um documento com vários textos
documentos = [
    "gato e cachorro",
    "gato brinca com cachorro",
    "gato e rato"
]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(documentos)
  # fit >> cria uma lista com cada palavra que existe no texto
  # transform >> transforma as palavras em um vetor

print("Matriz BoW: ", X.toarray())

print(f"Vocabulário: {vectorizer.vocabulary_}")

Matriz BoW:  [[0 1 0 1 0]
 [1 1 1 1 0]
 [0 0 0 1 1]]
Vocabulário: {'gato': 3, 'cachorro': 1, 'brinca': 0, 'com': 2, 'rato': 4}


## Exemplo 2 - Implementando o BOW junto com TF-IDF

In [ ]:
# importação das ferramentas que serão utilizadas
from sklearn.feature_extraction.text import CountVectorizer #BoW
from sklearn.feature_extraction.text import TfidfVectorizer # TF-IDF
  # Term Frequency - Inverse Document Frequency >>> frequência ponderada

documentos = [
    "O cachorro gosta de passear no parque",
    "O gato dorme no sofá o dia todo",
    "Cachorros e gatos podem ser bons amigos"
]

# Vetorização pelo BoW
vectorizer_bow = CountVectorizer() # instância da ferramenta
X_bow = vectorizer_bow.fit_transform(documentos) # vetorização do texto

# impressão do vetor e da matriz
print(f"Vocabulário BoW: {vectorizer_bow.vocabulary_}")
print("Matrix BoW:")
print(X_bow.toarray())

# Vetorização TF-IDF
vectorizer_tfidf = TfidfVectorizer() # instânciação da classe
X_tfidf = vectorizer_tfidf.fit_transform(documentos) # vetorização
  # fit
  # transform

#impressão dos vetores com frequência ponderada
print(f"\nVocabulário TF-IDF: {vectorizer_tfidf.vocabulary_}")
print("Matriz TF-IDF")
print(X_tfidf.toarray())

Vocabulário BoW: {'cachorro': 2, 'gosta': 9, 'de': 4, 'passear': 12, 'no': 10, 'parque': 11, 'gato': 7, 'dorme': 6, 'sofá': 15, 'dia': 5, 'todo': 16, 'cachorros': 3, 'gatos': 8, 'podem': 13, 'ser': 14, 'bons': 1, 'amigos': 0}
Matrix BoW:
[[0 0 1 0 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 1 1 1 0 0 1 0 0 0 0 1 1]
 [1 1 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0]]

Vocabulário TF-IDF: {'cachorro': 2, 'gosta': 9, 'de': 4, 'passear': 12, 'no': 10, 'parque': 11, 'gato': 7, 'dorme': 6, 'sofá': 15, 'dia': 5, 'todo': 16, 'cachorros': 3, 'gatos': 8, 'podem': 13, 'ser': 14, 'bons': 1, 'amigos': 0}
Matriz TF-IDF
[[0.         0.         0.42339448 0.         0.42339448 0.
  0.         0.         0.         0.42339448 0.32200242 0.42339448
  0.42339448 0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.42339448
  0.42339448 0.42339448 0.         0.         0.32200242 0.
  0.         0.         0.         0.42339448 0.42339448]
 [0.40824829 0.40824829 0.        

## Exemplo 3 - Aula 4 e aula 5
Exemplo de pré processamento e representação de texto com:
*   Limpeza de dados: removendo caracteres indesejados e normalizando o texto.
*   Tokenização: dividindo o texto em palavras individuais.
*   Remoção de StopWords:eliminando palavras comuns que não carregam significado semântico importante.
*   Lematização: reduzindo as palavras à sua forma base.
*   Representação de texto: convertendo o texto processado em uma matriz numérica usando o modelo Bag of Words.



In [5]:
# importação das bibliotecas
import nltk
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer

# donwload dos pacotes necessários
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

# criação dos documentos com vários textos
documentos = [
  "Os cachorros são animais muito amigáveis e leais!",
  "Eu gosto de gatos porque eles são independentes e fofos.",
  "Cachorros e gatos podem ser ótimos animais de estimaçãos. "
]

# inicialização do lematizador e lista de StopWords em português
lemmatizer = WordNetLemmatizer()
stop_words = set (stopwords. words ("portuguese"))

# criação de uma função para pré processamento do texto
def preprocessar_texto(texto):
  texto = re. sub(r'[^a-zA-Zá-ÿ\s]','',texto)
  tokens_tudo = word_tokenize(texto.lower())
  tokens = [palavra for palavra in tokens_tudo if palavra not in stop_words]
  tokens_lema = [lemmatizer. lemmatize(palavra) for palavra in tokens]
  return ' '. join(tokens_lema)

# aplicando o pré processamento nos documentos
documentos_processados = [preprocessar_texto(doc) for doc in documentos]

# exibindo os documentos processados
print ('documentos Pré-processados:')
for i, doc in enumerate (documentos_processados) :
  print (f"Documento {i + 1}: {doc}")

# transformando documentos processados em uma matriz BoW
vectorizer = CountVectorizer()
X_bow = vectorizer. fit_transform(documentos_processados)
print("\nVocabulario BoW:", vectorizer. vocabulary_)
print ("Matriz BoW:")
print (X_bow.toarray())

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


documentos Pré-processados:
Documento 1: cachorros animais amigáveis leais
Documento 2: gosto gatos porque independentes fofos
Documento 3: cachorros gatos podem ótimos animais estimaçãos

Vocabulario BoW: {'cachorros': 2, 'animais': 1, 'amigáveis': 0, 'leais': 8, 'gosto': 6, 'gatos': 5, 'porque': 10, 'independentes': 7, 'fofos': 4, 'podem': 9, 'ótimos': 11, 'estimaçãos': 3}
Matriz BoW:
[[1 1 1 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 1 0]
 [0 1 1 1 0 1 0 0 0 1 0 1]]
